### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by natefinch** [Richard-Weiss/Bing-Creator-Image-Downloader#22]
First wanted to say thank you for this. I can't believe there's no default way to download all the pictures from a Bing collection.  I've been using bing image create to make a bunch of images for my D&D game. I don't normally use bing for anything, so I didn't realize at first that the images weren't actually getting stored "in" my account per se, I was just saving some links.

Anyway... I ran your code locally on my MacOS machine, and the first time I ran it,  I got this result:

```
~/src/github.com/Richard-Weiss/Bing-Creator-Image-Downloader (main|✚1) % python ./main.py
2023-12-19 13:02:49,980 INFO Fetching metadata of collections...
Traceback (most recent call last):
  File "/Users/natefinch/src/github.com/Richard-Weiss/Bing-Creator-Image-Downloader/./main.py", line 565, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/natefinch/src/github.com/Richard-Weiss/Bing-Creator-Image-Downloader/./main.py", line 526, in main
    await bing_creator_image_download.run()
  File "/Users/natefinch/src/github.com/Richard-Weiss/Bing-Creator-Image-Downloader/./main.py", line 52, in run
    await self.__set_creation_dates()
  File "/Users/natefinch/src/github.com/Richard-Weiss/Bing-Creator-Image-Downloader/./main.py", line 217, in __set_creation_dates
    await asyncio.gather(*tasks)
  File "/Users/natefinch/src/github.com/Richard-Weiss/Bing-Creator-Image-Downloader/./main.py", line 258, in set_creation_date
    response_image_list = [img for img in images if img['imageId'] == decoded_image_id]

TypeError: 'NoneType' object is not iterable
```
Looks like the images collection was empty when getting image metadata? No other info in the debug log.

I started looking at the code, added a print line to see what response was coming back when getting the image metadata... and the second run Just Worked. ¯\\_(ツ)_/¯

Not sure what was going on that first time. Anyway, wanted to file this in case someone else runs into it, so you'll know if it's just a one time Me thing, or a more general problem.

Thanks again for this tool. I would be really sad if I lost access to all the images I created.

**Comment by Richard-Weiss** [comment]
@natefinch 
Looks interesting.
Basically it means that the `value` key in the response body for getting the creation date is empty for some unknown reason, even though the response is returning a 200.
There's nothing like `isSuccess` that exists for some 200 responses.
It's just some Microsoft API hijinks, but still thanks for bringing it up. :)
